services:
  postgres:
    build: .
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: recipe,collection,notification,users,ingredient,review

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 15s
        timeout: 30s
        retries: 5

  recipe-service:
    image: ghcr.io/thi-cnd/recipe_service:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
        DB_URL: jdbc:postgresql://postgres:5432/recipe
        DB_USER: postgres
        DB_PASSWORD: password
        RABBIT_HOST: rabbitmq
        RABBIT_PORT: 5672
        RABBIT_USER: guest
        RABBIT_PASSWORD: guest
    depends_on:
      - postgres
      - rabbitmq

  collection-service:
    image: ghcr.io/thi-cnd/collection_service:latest
    ports:
      - "8000:8000"
    environment:
        SECRET_KEY_DJANGO: django-insecure-vm$+=b8+s&54m6*yz*h&7m2b0nq_+ujg30akgs%+v5jw!p_=xg
        DB_NAME: collection
        DB_USER: postgres
        DB_PASSWORD: password
        DB_HOST: postgres
        DB_PORT: 5432
        RABBITMQ_USER: guest
        RABBITMQ_PASSWORD: guest
        RABBITMQ_HOST: rabbitmq
        USE_TEST_DB: False #Test Database
    restart: unless-stopped
    depends_on:
     postgres:
       condition: service_started
     rabbitmq:
       condition: service_healthy
    
  notification-service:
    image: ghcr.io/thi-cnd/notification_service:latest
    ports:
      - "8081:8081"
    environment:
        DB_URL: jdbc:postgresql://postgres:5432/notification
        DB_USER: postgres
        DB_PASSWORD: password
        RABBITMQ_USER: guest
        RABBITMQ_PASSWORD: guest
        RABBITMQ_HOST: rabbitmq
    restart: unless-stopped
    depends_on:
     postgres:
       condition: service_started
     rabbitmq:
       condition: service_healthy
  
  user-service:
    image: ghcr.io/thi-cnd/user_service:latest
    ports: 
      - 8082:8082
    environment:
      GIN_MODE: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: user
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    restart: unless-stopped
    depends_on:
     postgres:
       condition: service_started
     rabbitmq:
       condition: service_healthy

  
