
---
apiVersion: v1
kind: Service
metadata:
  name: collection-service
  namespace: recipe-app
spec:
  ports:
    - port: 8000
      name: http
    - port: 50051
      name: grpc
  selector:
    app: collection-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-service
  template:
    metadata:
      labels:
        app: collection-service
    spec:
      containers:
        - name: collection-service
          image: ghcr.io/thi-cnd/collection_service:latest
          ports:
            - containerPort: 8000
            - containerPort: 50051
          env:
            - name: SECRET_KEY_DJANGO
              value: "django-insecure-vm$+=b8+s&54m6*yz*h&7m2b0nq_+ujg30akgs%+v5jw!p_=xg"
            - name: DB_NAME
              value: "collection"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_EXCHANGE
              value: "recipemanagement"
            - name: RABBITMQ_ROUTING_KEYS_COLLECTION
              value: "collection.created,collection.updated,collection.deleted"
            - name: USE_TEST_DB
              value: "False"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collection-service-ingress
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: collection-service.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collection-service
                port:
                  number: 8086