
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: recipe-app
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/thi-cnd/user_service:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "users"
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"


---
apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  namespace: recipe-app
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: recipe-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: ghcr.io/thi-cnd/recipe_service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/recipe"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"

---
apiVersion: v1
kind: Service
metadata:
  name: collection-service
  namespace: recipe-app
spec:
  ports:
    - port: 8000
      name: http
    - port: 50051
      name: grpc
  selector:
    app: collection-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-service
  template:
    metadata:
      labels:
        app: collection-service
    spec:
      containers:
        - name: collection-service
          image: ghcr.io/thi-cnd/collection_service:latest
          ports:
            - containerPort: 8000
            - containerPort: 50051
          env:
            - name: SECRET_KEY_DJANGO
              value: "django-insecure-vm$+=b8+s&54m6*yz*h&7m2b0nq_+ujg30akgs%+v5jw!p_=xg"
            - name: DB_NAME
              value: "collection"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_EXCHANGE
              value: "recipemanagement"
            - name: USE_TEST_DB
              value: "False"


---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: recipe-app
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: notification-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/thi-cnd/notification_service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/notification"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_EXCHANGE
              value: "recipemanagement"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:UseSVE=0"

---
apiVersion: v1
kind: Service
metadata:
  name: ingredient-service
  namespace: recipe-app
spec:
  ports:
    - port: 8083
      name: http
  selector:
    app: ingredient-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredient-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredient-service
  template:
    metadata:
      labels:
        app: ingredient-service
    spec:
      containers:
        - name: ingredient-service
          image: ghcr.io/thi-cnd/ingredient_service:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/ingredient
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_PORT
              value: 5672
            - name: RABBIT_USER
              value: guest
            - name: RABBIT_PASSWORD
              value: guest

