
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: recipe-app
spec:
  ports:
    - port: 8085
      targetPort: 8080
      name: http
  selector:
    app: feed-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: ghcr.io/thi-cnd/feed_service:latest
          ports:
            - containerPort: 8080
          env:
            - name: RECIPE_SERVICE_URL
              value: "http://recipe-service:8080/api/v1/recipe"
            - name: COLLECTION_SERVICE_URL
              value: "http://collection-service:8000/collections"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"