---
apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  namespace: recipe-app
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: recipe-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: ghcr.io/thi-cnd/recipe_service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/recipe"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
