
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: recipe-app
spec:
  ports:
    - port: 8084
      targetPort: 8084
      name: http
  selector:
    app: review-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: ghcr.io/thi-cnd/review_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/review"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
